version: "3"
services:
  # tinacms:
  #   build: ./
  #   container_name: tinacms
  #   restart: unless-stopped
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.password.rule=Host(`$ZONE-password.erison.work`)"
    #   - "traefik.http.routers.password.entrypoints=websecure"
    #   - "traefik.http.services.password.loadbalancer.server.port=80"
    #   - "traefik.http.routers.password.tls.certresolver=cloudflare"
    # volumes:
    #  - $HOME_HOST/apps/vaultwarden/data:/data:rw
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
